### ISSUE TITLE
match the exactly candidate first

### ISSUE THREAD

**Issue by futurist** [PythonNut/company-flx#14]
When input `kbd` now the candidate popup is:

```
key-binding
kbd
........
```

In this case, should it the kbd as first candidate?

similar case, when input `setq`

```
select-tags-table-quit
setq
```

**Comment by PythonNut** [comment]
That's strange because, as far as I know, exact matches should always get priority. Let me look into it.

**Comment by PythonNut** [comment]
@futurist For me, `kbd` matches `kbd` first. Are you sure something isn't interfering with your sorting?

**Comment by futurist** [comment]
below is my config with company-flx:

``` lisp

(require-package 'company)
(require-package 'company-flx)
(require-package 'company-tern)
(require-package 'company-quickhelp)
(add-hook 'after-init-hook 'global-company-mode)
(setq company-idle-delay 0)
(setq company-minimum-prefix-length 2)
(after-load 'company
  (company-flx-mode +1)
  (setq company-auto-complete t)
  (setq company-flx-limit 15)
  (define-key company-active-map (kbd "<SPC>") '(lambda()(interactive) (company-abort) (insert " ")))
  (define-key company-active-map (kbd "C-j") 'company-abort)
  (define-key company-active-map (kbd "<tab>") 'company-complete-common-or-cycle)
  (define-key company-active-map "\C-n" 'company-select-next-or-abort)
  (define-key company-active-map "\C-p" 'company-select-previous-or-abort)
  )
(after-load 'company-tern
  (add-to-list 'company-backends 'company-tern)
  )

```

**Comment by futurist** [comment]
I think the problem maybe is the `(setq company-minimum-prefix-length 2)`
<kbd>kb</kbd> will trigger company first, then with third key <kbd>d</kbd>, the sort order don't changed.

**Comment by PythonNut** [comment]
> I think the problem maybe is the `(setq company-minimum-prefix-length 2)`

I don't think so because I also use that setting. I'll take a look today, if I get the chance.

**Comment by PythonNut** [comment]
To confirm, I still can't reproduce.
