### ISSUE TITLE
Please release company-flx on MELPA stable

### ISSUE THREAD

**Issue by ghost** [PythonNut/company-flx#16]
company-flx hasn't seen a release on [MELPA stable](https://stable.melpa.org/) yet. Please consider releasing company-flx on MELPA stable.

**Comment by PythonNut** [comment]
Hi @sixpointzero. I'll look into it. My job is crazy right now, and I haven't had much time for OSS stuff. :)

**Comment by ghost** [comment]
It's fine. I'll keep using the version on MELPA for now :)

**Comment by PythonNut** [comment]
Maybe some day...
