### ISSUE TITLE
company-flx isn't available after install

### ISSUE THREAD

**Issue by mattiasb** [PythonNut/company-flx#3]
`company-flx-mode` isn't available after install from melpa. I can't start it via M-x and it fails with

```
Symbol's function definition is void: company-flx-mode
```

if I add

```
(with-eval-after-load 'company
  (company-flx-mode +1))
```

to my init.el.

**Comment by PythonNut** [comment]
Sorry. That's because I failed to include the correct autoload annotation. I'll fix it asap.
