### ISSUE TITLE
Type error when completing

### ISSUE THREAD

**Issue by mattiasb** [PythonNut/company-flx#4]
I'm getting this warning when completing with company with `company-flx-mode` enabled:

```
Company: An error occurred in auto-begin
Wrong type argument: hash-table-p, "Stores company-mode's flx-cache"
```

This is with the latest melpa release (20151018.1428).

**Comment by ssbb** [comment]
Can reproduce it

**Comment by PythonNut** [comment]
Sorry, a bit of shortsight on my part.

**Comment by ssbb** [comment]
Thanks! Should I wait for melpa update or it will be better to use git sources?

**Comment by PythonNut** [comment]
@ssbb whichever you prefer.

**Comment by ssbb** [comment]
@PythonNut I mean that it's still unfixed version only available via melpa.

**Comment by PythonNut** [comment]
I can't hurry up the MELA rebuild, sadly.
