### ISSUE TITLE
How should company-flx work?

### ISSUE THREAD

**Issue by mattiasb** [PythonNut/company-flx#6]
Since the latest melpa release I'm now able to load `company-flx` (yay!). But how is it supposed to work?
In the example below I would have expected to be able to type "conran" and get `windmove-constrain-to-range` as the only option left. Though when I type I get a beep from emacs and no progress.

![screenshot from 2015-10-19 20-34-07](https://cloud.githubusercontent.com/assets/1341313/10587315/cafffeec-76a0-11e5-8b83-e0aa78b22865.png)

Could you upload a video to youtube or add a gif animation to README.md explaining how it should work?

Thanks in advance
Mattias

**Comment by PythonNut** [comment]
@mattiasb Hm... something seems to be amiss. It should work intuitively.

Sorry, most of my attention has been on `helm-flx` ATM.

**Comment by PythonNut** [comment]
@mattiasb strange... it's working for me in `emacs24.5 -Q`.

> Could you upload a video to youtube or add a gif animation to README.md explaining how it should work?

I could... but there's a lot of effort involved in making a GIF on my current setup, so that might have to wait a bit.

**Comment by mattiasb** [comment]
Got it working with emacs -Q so definitely a problem in my config somewhere. Sorry for the noise. :)

**Comment by PythonNut** [comment]
If you find out what it is, please report back. If there's anything I can do to accommodate your config, I'll consider adding it. :)

**Comment by mattiasb** [comment]
Great, thanks! :)
